### ISSUE TITLE
Create php file instead html

### ISSUE THREAD

**Issue by yoanmalie** [itgalaxy/favicons#138]
Hello,
If i want a .php file instead .html but i have many 0000 characters in it, not HTML code.

I use gulp-favicons.

config:

```
html: '../../favicons.php',
pipeHTML: true,
replace: true,
```

This is what i have in my favicons.php file:

```
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 00
```

**Comment by yoanmalie** [comment]
Hello,

Perhaps i was not clear enough, here some infos:
- node v4.2.6
- npm v3.5.2
- gulp (cli and locale) v3.9.1
- gulp-favicons v2.2.6

Running on Ubuntu 16.04 64bit

Why i can't create a .php file instead .html ?
If you need others information, tell me which one.

Thank

**Comment by S1SYPHOS** [comment]
I'd be happy to see this, too :rice_ball:

**Comment by evilebottnawi** [comment]
PR welcome :+1:

**Comment by S1SYPHOS** [comment]
@yoanmalie: In the meantime, you may use `gulp-filter` to accomplish what you are looking for (I'll leave it here for future seekers):

```js
gulp.task('favicons', function() {
  const htmlFilter = filter('**/index.html', {restore: true});
  const options = { /* some options */ };
  return gulp.src('path/to/favicon.svg')
    .pipe(favicons(options))
    .pipe(htmlFilter)
    .pipe(rename({extname: '.php'})) // gulp-rename FTW
    .pipe(htmlFilter.restore)
    .pipe(gulp.dest('dist'));
});
```
