### ISSUE TITLE
Check the icons generated in the manifest.

### ISSUE THREAD

**Issue by disjfa** [itgalaxy/favicons#217]
If i check a site using the data from this bundle and check the data in the https://www.pwabuilder.com they "suggest" some missing icons for ios and microsoft:

> Missing image group:
>  It appears that some image sizes used on Windows 10 are not in your Manifest. We will leave off any we can, and add defaults for any necessary images that are missing Platforms affected:windows10.
> 
> Missing image:
>  An app icon of the following sizes is required: 76x76, 120x120, 152x152 and 180x180 Platforms affected:ios.
> 
>  Missing image:
>  An 1024x1024 app icon for the App Store is required Platforms affected:ios.
> 
>  Missing image:
>  A launch image of the following sizes is required: 750x1334, 1334x750, 1242x2208, 2208x1242, 640x1136, 640x960, 1536x2048, 2048x1536, 768x1024 and 1024x768 Platforms affected:ios.
> 
>  Missing image group:
>  It appears that some image sizes used on Windows 10 are not in your Manifest. We will leave off any we can, and add defaults for any  necessary images that are missing Platforms affected:windows.

I that would be ok we can update the json files.

Btw, awesome that there is some action again in this repo!

**Comment by brunocodutra** [comment]
Sounds great, would you volunteer for a PR @disjfa?
