### ISSUE TITLE
No option for short_name

### ISSUE THREAD

**Issue by jesperlehtinen** [itgalaxy/favicons#219]
There's no config option for `short_name` in manifest.json. Currently it takes the application name, which might be too long (recommended max. length for `short_name` is 12 chars, according to https://developer.chrome.com/apps/manifest/name#short_name).

**Comment by tommytomatoe** [comment]
I submitted a pull request for this.

**Comment by evilebottnawi** [comment]
Done in master, will release in nexr future, feel free to ping pe
