### ISSUE TITLE
Plans to remove PhantomJS dependency

### ISSUE THREAD

**Issue by patrickberkeley** [itgalaxy/favicons#221]
This package relies on svg2png. svg2png uses PhantomJS which [has been sunsetted](https://github.com/ariya/phantomjs/issues/15344).

Are there any plans to remove the svg2png/PhantomJS dependency from this package?

**Comment by lovell** [comment]
Hello, I've had a (very) quick look at whether sharp/libvips/librsvg might be suitable to replace PhantomJS in the context of SVG rendering in this module.

At the moment the tests rely on snapshots that require pixel values to be an exact match.

Switching to a testing approach that verifies based on image similarity, with a suitable threshold, could help not only with a migration away from PhantomJS but also with a possible future move to a plugin-based approach where different renderers might be considered. Happy to help if this is something that others think is suitable.
