### ISSUE TITLE
Option to disable injection of HTML

### ISSUE THREAD

**Issue by fabe** [itgalaxy/favicons#227]
Is there a way to disable the injection of the HTML? I'd like to use `favicons` only for the creation of the files. Would you accept a PR for this? Thanks!

**Comment by evilebottnawi** [comment]
@fabe feel free to PR

**Comment by fabe** [comment]
Seems like I mistakenly thought that the HTML is injected when this log comes up:

```bash
[Favicons] HTML:parse: HTML found, parsing and modifying source...
```

Nothing is actually injected 👍
