### ISSUE TITLE
apple-mobile-web-app-status-bar-style is always set to black-translucent

### ISSUE THREAD

**Issue by brunocodutra** [itgalaxy/favicons#230]
The initial value of the meta property [`applt-mobile-web-app-status-bar-style` is `black_translucent`](https://github.com/itgalaxy/favicons/blob/master/src/config/html.json#L19), however it probably should be set to `theme_color` around [this line](https://github.com/itgalaxy/favicons/blob/master/src/helpers.js#L132).

**Comment by dangreen** [comment]
You can't set any color by this tag. Read the docs.
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html#//apple_ref/doc/uid/TP40008193-SW2

**Comment by uwolfer** [comment]
Implemented, see PR  #231.
