### ISSUE TITLE
Wrong order of icons

### ISSUE THREAD

**Issue by Exelord** [itgalaxy/favicons#234]
Because of the wrong order of icons chrome is loading every icon until it met his expectations in every navigation change.
<img width="703" alt="screen shot 2018-08-25 at 21 55 31" src="https://user-images.githubusercontent.com/1469375/44624963-c144f600-a8b1-11e8-8f9f-48313744f229.png">

HTML:
<img width="578" alt="screen shot 2018-08-25 at 21 57 07" src="https://user-images.githubusercontent.com/1469375/44624968-d7eb4d00-a8b1-11e8-8ea0-f62d6df3c89a.png">

icons should be ordered: `favicon -> 16x -> 32x`

Issue Ref: https://github.com/ctrlplusb/react-universally/issues/145

**Comment by uwolfer** [comment]
Fix has been merged (#235). Issue can be closed.

@Exelord: Thanks for the detailed issue description.

**Comment by Exelord** [comment]
Thank you! Great job! :)

**Comment by Exelord** [comment]
Could you release that in version?
