### ISSUE TITLE
Allow to generate HTML without  generating files

### ISSUE THREAD

**Issue by Exelord** [itgalaxy/favicons#238]
It would be nice to have an option to generate HTML output based on passed options without generating favicons files.

Expected API:
```js
let favicons = new Favicons(options);
favicons.html // returns generated html
favicons.generateFiles() // generate all files
```

As those tasks are totally independent it would be nice to have a separate access to get the ability to better manipulate the data and write better integrations.

**Comment by mattpr** [comment]
It used to be that you could programmatically get the html from the config object but looks like this changed with this commit:
https://github.com/itgalaxy/favicons/commit/ad4816c20603f00e183721f9ddfb0c59e1afa2fb

Used to be you could do something along the lines of the following to grab html snippets for each icon type.  You could check against the config to see which icon types are enabled as well to make this completely dynamic.  ie get html for configured favicons lib even if the images have not been generated yet.
```javascript
let faviconConfig = require('favicons').config, 
    iconHtml = '';
//...
for (var key in faviconConfig['html']['favicons']) {
        if (faviconConfig['html']['favicons'].hasOwnProperty(key)) {
            iconHtml += faviconConfig['html']['favicons'][key];
        }
}
//...
```

This part of the config api was changed between 5.3 and 5.4.

The readme still says you can programmatically retrieve html from the config object but as there doesn't seem to be much documentation on the many options here...I still have to spend some time reading the code.
