### ISSUE TITLE
Unable to generate multiple favicons from multiple source files

### ISSUE THREAD

**Issue by firestar300** [itgalaxy/favicons#239]
favicons version used : **5.1.1**

Hello there,
I found this PR : https://github.com/itgalaxy/favicons/pull/98

Actually, I would like to generate favicons from multiple source files. In my src folder, I have theses source files :
```
src
|- tsg-favicon.png
|- tsh-favicon.png
```

And I expected to generate favicons from tsg-favicon.png to the path `./dist/assets/img/favicons/tsg` and favicons from tsh-favicon.png to `./dist/assets/img/favicons/tsh`.

```javascript
const favicons = require('favicons')
const fs = require('fs')
const faviconPath = 'src/img/favicons/'
const faviconSource = ['tsg-favicon_src.png', 'tsh-favicon_src.png']

let configuration = {
  path: './dist/assets/img/favicons',
  url: 'http://beapi.fr',
  display: 'standalone',
  orientation: 'portrait',
  version: 1.0,
  logging: false,
  online: false,
  pipeHTML: true,
  replace: true,
}

faviconSource.map(favicon => {
  if (favicon.indexOf('tsg') > -1) {
    configuration.path = './dist/assets/img/favicons/tsg'
  } else if (favicon.indexOf('tsh') > -1) {
    configuration.path = './dist/assets/img/favicons/tsh'
  }
  favicons(faviconPath + favicon, configuration, callback)
})
```

Unfortunately, all favicons are generated into `'./dist/assets/img/favicons/tsh'`

Did i missed something ?

**Comment by andy128k** [comment]
@firestar300 probably your problem is because you share configuration between two processes.
