### ISSUE TITLE
Dependencies on favicons in an ES3 TypeScript project will cause build failures

### ISSUE THREAD

**Issue by jameswilddev** [itgalaxy/favicons#246]
favicons has a dependency on cheerio 1.0.0-rc.2, which itself has a dependency on parse5 3.0.3, which itself has a dependency on types/node.  The result of this is that installing favicons installs types/node, which means that the TypeScript compiler uses those types when compiling, even if the target is ES3, causing compile errors ([similar to this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24595)).

Parse5 itself fixed this long ago, but cheerio was never updated to use the newest version which contains the fix.  I've raised cheeriojs/cheerio/issues/1245 to get this resolved, but cheerio currently appears to have quite a long release schedule, so downgrading to 0.2.2 will fix this for any dependencies.

Currently trying to figure out how to translate the current usage of cheerio 1.0.0-rc2 into its equivalent for cheerio 0.2.2 to raise a PR, but unfamiliar with either API.

**Comment by jameswilddev** [comment]
Just looking at why I couldn't get the tests to pass; every test hitting that section of code seems to handle a value from src/config/html.json, such as:

```html
<link rel='shortcut icon' href='favicon.ico'>
```

The selector is:

```js
const tag = $("*", "head").first();
```

My interpretation of this [based on the documentation](https://github.com/cheeriojs/cheerio#-selector-context-root-) is "the first element of any sort inside the head element".

This doesn't quite seem to match up; might need some help here to understand this.

**Comment by evilebottnawi** [comment]
@jameswilddev It is not high priority feel free to send a Pr with fix

**Comment by jameswilddev** [comment]
I'm no longer using this within an ES3 project; sorry, not sure.
