### ISSUE TITLE
TypeError: dest.on is not a function

### ISSUE THREAD

**Issue by dslpp056193** [itgalaxy/favicons#262]
Error:
![image](https://user-images.githubusercontent.com/11080873/56471944-121ce680-6461-11e9-8a0f-d45426ba6e50.png)

Gulpfile:
![image](https://user-images.githubusercontent.com/11080873/56471953-38db1d00-6461-11e9-868e-4c9b131fef38.png)

**Comment by dslpp056193** [comment]
My bad, i forget about `.stream` property at `require('favicons')`

**Comment by evilebottnawi** [comment]
@dslpp056193 can we close issue?

**Comment by dslpp056193** [comment]
@evilebottnawi of course, close it. Thanks!
