### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by richardklose** [itgalaxy/favicons#263]
Currently there is not yet a release that contains the changes of #254. Are there any plans on creating a new release with this changes in the near future? 

Currently our code is depending on the latest commit on master but I'd be happier with an actual release to depend on.
Depending on a commit from GitHub means the code will always be downloaded from GitHub on `npm install` but with a release on npm, the download will be cached by our company hosted npm registry.

**Comment by ahukkanen** [comment]
I'm also waiting for the fixes at #252.
