### ISSUE TITLE
Outdated content

### ISSUE THREAD

**Issue by lucasvazq** [itgalaxy/favicons#282]
manifest.webapp

Firefox OS doesn't exist anymore

https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/Firefox_OS_apps/Building_apps_for_Firefox_OS/Manifest

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by lucasvazq** [comment]
@evilebottnawi I can't right now, in a week

**Comment by lucasvazq** [comment]
@andy128k Good job, I completely forgot about this
