### ISSUE TITLE
Prepare for react 17, change use of componentWillMount()

### ISSUE THREAD

**Issue by stheine** [itgalaxy/favicons#283]
After updating to react 16.9.0, there is the warning:

Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Favicon

**Comment by evilebottnawi** [comment]
What? It is not react repo
