### ISSUE TITLE
Update deps

### ISSUE THREAD

**Issue by janosh** [itgalaxy/favicons#286]
Would you accept a PR to update dependencies? In particular `sharp` to avoid [version mismatch issues](https://github.com/gatsbyjs/gatsby/issues/16957#issuecomment-536163039) with more up-to-date packages?

**Comment by evilebottnawi** [comment]
Yes, feel free to send a PR

**Comment by JulianBerger** [comment]
Check #290

**Comment by evilebottnawi** [comment]
Done
