### ISSUE TITLE
5.5.0 includes breaking change

### ISSUE THREAD

**Issue by jantimon** [itgalaxy/favicons#293]
I tried upgrading to 5.5.0 however it seems node 6 is no longer supported.

Unfortunately with that change it is not compatible with the webpack 4.x ecosystem anymore.

<img width="474" alt="webpack" src="https://user-images.githubusercontent.com/4113649/69829918-6a4f6e80-1222-11ea-907e-6bd1c4857f36.png">

As this is a breaking change it should probably be released as favicons 6.0

**Comment by evilebottnawi** [comment]
It is not breaking change :smile: we have https://github.com/itgalaxy/favicons/blob/master/package.json#L46 a long time :smile: I think it is time to do breaking change in `favicons-webpack-plugin`, node@6 is very old and very few developers use it, a lot of loaders/plugins already require node@10, but have compatibility with webpack@4, i am afraid what packages which we use require node@8 and we can't easy downgrade them

**Comment by jantimon** [comment]
@evilebottnawi 

5.4.1 was without that engine entry:

https://github.com/itgalaxy/favicons/blob/049f3a1325035480a2e63245f639673653ff0898/package.json

so if 5.4.1 supports node 6 and the current version removes node 6 support it is a breaking change

**Comment by evilebottnawi** [comment]
@jantimon agreen, but now our dependencies require node@8 and we can't downgrade them to `6` :disappointed: any ideas?

**Comment by jantimon** [comment]
That's fine - maybe release as 6.0 so semantic versioning is correct again.

Do you know if any older version of favicons is compatible to node 6?

**Comment by evilebottnawi** [comment]
@jantimon :+1: 
5.4 should have compatibility with node@6
