### ISSUE TITLE
Favicons name hashing

### ISSUE THREAD

**Issue by georgyfarniev** [itgalaxy/favicons#294]
Hello. Please add support of hashing for icon filenames, this is very imporant feature, this is how caching works everywhere now.

I use it via webpack plugin and I have no options to solve this problem :(

@evilebottnawi, consider adding just callback function (optional) that can modify output file name. Could be useful!

**Comment by georgyfarniev** [comment]
@evilebottnawi, can you please review PR for this? I need it so much. Thanks in advance, and thanks for working on this module.

**Comment by evilebottnawi** [comment]
Please open issue in webpack plugin

**Comment by georgyfarniev** [comment]
@evilebottnawi, after checking code of favicons I realized that it has to be done in webpack plugin. Thank you for quick response.
