### ISSUE TITLE
Error after multiple runs within a short time

### ISSUE THREAD

**Issue by gawlk** [itgalaxy/favicons#295]
Hi,

There is an error if we don't wait too long before relaunching the library:

```bash
Error: Input buffer has corrupt header: vips_realpath: unable to form filename
unix error: No such file or directory
glib: SVG has no elements

glib: SVG has no elements
```

Is this normal ?

Here's my config

```json
{
    "path": "/assets/favicons/",

    "appName": "svind",
    "appShortName": "svind",
    "appDescription": "description",
    "developerName": null,
    "developerURL": null,

    "background": "#1db9ce",
    "theme_color": "#1db9ce",
    "appleStatusBarStyle": "black-translucent",

    "url": "https://svind.now.sh",
    "start_url": "/",

    "display": "standalone",
    "orientation": "portrait",

    "logging": false,
    "html": "icons.html",
    "pipeHTML": true,
    "replace": true,

    "icons": {
        "android": { "offset": 5 },
        "appleIcon": { "offset": 5 },
        "appleStartup": { "offset": 20 },
        "coast": false,
        "favicons": { "offset": 5 },
        "firefox": { "offset": 10 },
        "windows": { "offset": 5 },
        "yandex": false
    }
}
```

**Comment by evilebottnawi** [comment]
Can you create reproducible test repo?

**Comment by gawlk** [comment]
Sure here it is: https://github.com/gawlk/favicons-lib-error-demo

Here's the whole error message 

```
[00:30:05] Error: Input buffer has corrupt header: vips_realpath: unable to form filename
unix error: No such file or directory
glib: SVG has no elements


[00:30:05] 'default' errored after 51 ms

(sharp:70994): GLib-CRITICAL **: 00:30:05.824: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:70994): GLib-CRITICAL **: 00:30:05.824: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

(sharp:70994): GLib-CRITICAL **: 00:30:05.824: g_hash_table_lookup: assertion 'hash_table != NULL' failed
```

Although it seem to be svg related, I couldn't reproduce it when generating favicons from a png

**Comment by evilebottnawi** [comment]
What is version you use?

**Comment by gawlk** [comment]
Favicons 5.5 the same as in the repo

**Comment by evilebottnawi** [comment]
hm, all fine, can you try to reinstall deps? Maybe something wrong with environment (with `sharp`)

**Comment by gawlk** [comment]
Not possible, I had the error with 2 different codebases and I created this repo from scratch few hours ago

**Comment by evilebottnawi** [comment]
I don't have idea what is wrong :confused:

**Comment by gawlk** [comment]
It's ok ! Maybe it's my laptop somehow 🤔

**Comment by aarree** [comment]
Hi @gawlk ,
I had the same problem. The problem on my end was that I installed favicon over terminal and startet the task over the IDE with a different node version. The task must run with the same node Version it was build with.

Bit late, but I hope it helps!

**Comment by gawlk** [comment]
@aarree sadly everything has the same node version but thanks

**Comment by WuglyakBolgoink** [comment]
this happen not only after multiple times... on my macbook I have this error every time after start webstorm. after 2-3x times plugin create images correctly. on our build server (gitlab) we never had this error...  🤦🏻‍♂️

**Comment by gawlk** [comment]
@WuglyakBolgoink Do you have the latest version ? It seems to be ok for me now

**Comment by Michael-1** [comment]
I could solve the problem by removing the XML tag on the first line of the favicon SVG file.

**Comment by andrewplummer** [comment]
Having the same issue... removing the XML tag seems to fix it
