### ISSUE TITLE
Error when loading

### ISSUE THREAD

**Issue by Moritz-Topp** [itgalaxy/favicons#310]
Hey :D

My Setup:
I am using npm with Vue. In dev I run `npm run serve`.
My Production is using Docker, where I first build the dist and load them into nginx.

Problems:
When I open the page over npm serve this happens:
`Uncaught TypeError: fs.readdirSync is not a function`

In addition I got an Console Error when running npm run serve:
`in ./node_modules/sharp/build/Release/sharp.node
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./node_modules/sharp/lib/constructor.js 11:2-40
 @ ./node_modules/sharp/lib/index.js
 @ ./node_modules/favicons/dist/helpers.js
 @ ./node_modules/favicons/dist/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.188.13:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js`

And I don't know how to fix any of them. Do I need to host over Webpack?

Would be really nice if some of you know how I/ we can fix this :D

**Comment by evilebottnawi** [comment]
No related, it is webpack plugin problem
