### ISSUE TITLE
How to minify manifest.json file and optimize logo image with webpack loader? how to give assets name py pattern `name-[hash].ext` for forever caching?

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [itgalaxy/favicons#319]
How to minify manifest.json file and optimize logo image with webpack loader? how to give assets name py pattern `name-[hash].ext` for forever caching?

**Comment by evilebottnawi** [comment]
For images we prepare https://github.com/webpack-contrib/image-minimizer-webpack-plugin (release will be on this week), after this we will implement `json-minizer-webpack-plugin` for compressing json assets, this questions is not related to `favicons` package directory

**Comment by MaxmaxmaximusAWS** [comment]
@evilebottnawi  Regarding, my question is not related to image compression, and json compression. My question is related to: why does the "favicons" package NOT compress json and does NOT compress images? The site https://gtmetrix.com lowers my points for only two things, the logos created by the "favicons" library and "manifest.json" created by the "favicons" bubble library. That's why I wrote here.

**Comment by evilebottnawi** [comment]
You can use `imagemin` for this, it is out of scope pachage, we just generator

**Comment by MaxmaxmaximusAWS** [comment]
@evilebottnawi don't you want to make a webpack plugin?

**Comment by evilebottnawi** [comment]
@MaxmaxmaximusAWS We already doing it https://github.com/webpack-contrib/image-minimizer-webpack-plugin

**Comment by MaxmaxmaximusAWS** [comment]
@evilebottnawi We are not talking about image compression, and we are not talking about json compression. We are talking about the GENERATION of images, and the GENERATION of mainfest.json, which will THEN go to webpack assets and then people will decide what to do with them =)

No favicons and webpack integrations exist right now. (And the integration that is, it does not add generated images and manifest.json to webpack assets, and therefore webpack loaders will not be applied to what generates favicons)

You need to create a new, deeply integrated WebpackFaviconsPlugin, or even better WebpackPWAPlugin
(those that are now use the assets webpack system poorly)

Do you understand what I mean?) If you do not understand what I mean, then I will just write this plugin myself, but I think you have more experience with this.

**Comment by evilebottnawi** [comment]
> https://www.npmjs.com/package/imagemin-webpack-plugin

No caches and persistent caches, very slow + you can't minify embedded images (`url-loader`) + deps are hardcoded

> https://www.npmjs.com/package/image-webpack-loader

No compressed assets if you using `copy-webpack-plugin` + no caches and persistent cache + deps are hardcoded

Do you search https://github.com/jantimon/favicons-webpack-plugin?

**Comment by MaxmaxmaximusAWS** [comment]
@evilebottnawi Do you search https://github.com/jantimon/favicons-webpack-plugin?

Он является просто оберткой над вот этим вашем пакетом "favicons", и не добавляет ни какую интеграцию с webwpack системой лоадеров. Все мои картинки и все мои json имеют лоадеры и сжимаются, но картинки и manifest.json сгенерированный favicons-webpack-plugin не пропускает их через систему webpack полноценно =) я по этому и обратился к вам с предложением, может запилим нормаьный WebpackPWA генератор? Который и иконки генерирует и манифест, и глубоко интегрируется с вебпаком.

**Comment by evilebottnawi** [comment]
@MaxmaxmaximusAWS Да, судя по всему это хорошая идея, нашел еще https://github.com/arthurbergmz/webpack-pwa-manifest, но он не использует текущий пакет, мы можем начать это, я  вижу только положительные стороны этого плагина

**Comment by evilebottnawi** [comment]
Честно говоря я бы даже положил его `webpack-contrib` и сделал официальный решением, возможно нам потребуется небольшая работа здесь тоже, например кэширование

**Comment by MaxmaxmaximusAWS** [comment]
Кстати, на счет "как сжать `manifest.json`", вот так:

```javascript
class MinifyJSONWebpackPlugin {
  apply(compiler) {
    compiler.hooks.emit.tap(this.constructor.name, ({assets}) => {
      for (let filename in assets) {
        if (!assets.hasOwnProperty(filename)) continue
        if (!/\.json$/.test(filename)) continue
        const json = assets[filename].source().toString()
        const jsonMinified = JSON.stringify(JSON.parse(json))
        assets[filename] = new RawSource(jsonMinified)
      }
    })
  }
}
```

Только надо чтобы этот плагин шел после плагина генерирующего иконки)
