### ISSUE TITLE
Replace JIMP with Sharp?

### ISSUE THREAD

**Issue by Meisolsson** [itgalaxy/favicons#329]
From looking at the project there seems to be two image manipulation libraries JIMP and Sharp. And while I understand that the project wants no external dependencies, since it already uses sharp for parts of the pipeline why not everywhere. Sharp is [much faster than JIMP](https://sharp.pixelplumbing.com/performance#results) and since that speed is there why not use it?

**Comment by alexander-akait** [comment]
We have `sharp` and `jimp` :smile: Feel free to refactor code and drop `jimp`
