### ISSUE TITLE
Localized manifest?

### ISSUE THREAD

**Issue by raymondsze** [itgalaxy/favicons#354]
Even with https://github.com/itgalaxy/favicons/pull/348. Seems like it is insufficient to support localized manifest.
I did some search on stackoverflow and seems the normal practice for localized manifest is like this.
`<link rel="manifest" href="/en/manifest.json">`
For example, if the user browse the Chinese version of the website, it becomes
`<link rel="manifest" href="/zh/manifest.json">`
99% of cases we would use the same favicons for different locales. It seems a waste of resource if we generate duplicated images under the `en` and `zh` folder. (But it is good we could also support the 1% case that the website may have different set of favicons for different locales.)

I don't have any feature idea on how to implement this right now, but it is good if this library could support it.

**Comment by andy128k** [comment]
Placing manifest file into a subdirectory complicates the story. But with #361 you could do following:

1. generate all images by running with `{ output: { files: false, html: false } }`
2. generate English html and manifest with `{ output: { images: false }, files: { android: { manifestFileName: "manifest-en.json" } } }`
3. generate Chinese html and manifest with `{ output: { images: false }, files: { android: { manifestFileName: "manifest-zh.json" } } }`
