### ISSUE TITLE
Dead platforms

### ISSUE THREAD

**Issue by andy128k** [itgalaxy/favicons#362]
Firefox OS is dead. Opera Coast is also dead.

Should this library disable them by default? Or maybe remove their support totally?

**Comment by alexander-akait** [comment]
I think we can remove them safely

**Comment by andy128k** [comment]
I just realized that removal of support of Firefox OS makes big set options and functionality unused (`mask`, `overlayGlow`, `overlayShadow`).

**Comment by alexander-akait** [comment]
It is very good
