### ISSUE TITLE
heads up: broken colors package

### ISSUE THREAD

**Issue by DanielRuf** [itgalaxy/favicons#370]
https://github.com/webpack/webpack/issues/15130#issuecomment-1008163400
https://github.com/Marak/colors.js/issues/285

**Comment by agusterodin** [comment]
Same here. Console gets completely spammed indefinitely when running a project that uses this library.

**Comment by DanielRuf** [comment]
@agusterodin see https://github.com/Marak/colors.js/issues/285#issuecomment-1008168237 for some possible solutions.

If needed I can prepare the relevant patch.

**Comment by rsadr0pyz** [comment]
**npx marak-free**

**Comment by agusterodin** [comment]
I have no idea what that package is. Potentially dangerous given how weird things have been from Marak. Use caution when running commands with npx.

**Comment by DanielRuf** [comment]
@agusterodin see https://unpkg.com/browse/marak-free@1.0.1/ and https://unpkg.com/browse/marak-free@1.0.1/index.js

**Comment by xoxys** [comment]
Other seems to replace colors with chalk e.g. https://github.com/aws/aws-cdk/issues/18329 maybe that's a more reliable solution.

**Comment by DanielRuf** [comment]
> Other seems to replace colors with chalk e.g. [aws/aws-cdk#18329](https://github.com/aws/aws-cdk/issues/18329) maybe that's a more reliable solution.

Not in most cases as this might lead to breaking changes. The returned strings are a bit different and parsers may behave differently. See for example https://github.com/cli-table/cli-table3/pull/250#issuecomment-1008281148

The easier and faster fix is to pin the version since you can not remove or change already published package versions.

**Comment by DanielRuf** [comment]
> How does pinning solve the issue in a long term? In case of a future security issue you might end up locked, no idea if and how the colors package will be maintained in the future

> The easier and faster fix

I never said "longterm" fix. The longterm solution would be to switch to something like `chalk`, which is actively maintained.

Alternatively switch to the fork (DABH is one of its previous contributors and maintainers): https://www.npmjs.com/package/@dabh/colors

**Comment by xoxys** [comment]
Ok then we talk about the same thing now :) because what I said initially was 

> Other seems to replace colors with **chalk** e.g. aws/aws-cdk#18329 maybe that's a **more reliable solution.**

where `more reliable` means long term/permanent fix and not hotfix.
