### ISSUE TITLE
Upgrade to `sharp` 0.33.0

### ISSUE THREAD

**Issue by xavierfoucrier** [itgalaxy/favicons#446]
Thanks for this great package 🎉 

Unfortunately, since version 0.33.0, `sharp` team has changed the way the library is installed. When using `sharp` side by side with this package, or with a package using this package as a dependency, like `favicons-webpack-plugin`, there is some conflicts.

It would be nice to upgrade to the latest version of `sharp`.
Thanks for your feedback!

> See this related issue: https://github.com/lovell/sharp/issues/3878#issuecomment-1838626767.
> NPM related issue: https://sharp.pixelplumbing.com/install#npm.

**Comment by andy128k** [comment]
Updated in 7.1.5

**Comment by xavierfoucrier** [comment]
Thanks @andy128k 🎉
